-- Initial Migration: Create assessments table and RLS policy

CREATE TABLE IF NOT EXISTS assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    area_of_interest TEXT NOT NULL,
    soft_skills TEXT,
    tech_skills TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;

-- Create policy for full public API read and insert permissions
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'assessments' AND policyname = 'Allow public read and insert'
    ) THEN
        CREATE POLICY "Allow public read and insert" ON assessments
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
